export const instagram = <i className="fa-brands fa-instagram"></i>
export const twitter = <i className="fa-brands fa-twitter"></i>
export const youtube = <i className="fa-brands fa-youtube"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const edit = <i className="fa-solid fa-pen-to-square"></i>
export const check = <i className="fa-solid fa-check"></i>
export const times = <i className="fa-solid fa-xmark"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const sun = <i className="fa-regular fa-sun"></i>
export const moon = <i className="fa-regular fa-moon"></i>
export const badge = <i className="fa-solid fa-certificate"></i>
export const mail = <i className="fa-solid fa-envelope"></i>
export const profile = <i className="fa-solid fa-user"></i>
export const home = <i className="fa-solid fa-house"></i>